### PR TITLE
Port to Configs.json

### PR DESCRIPTION
**Pull request by leagris**
Made necessary changes to process Configs.json instead of Configs.xml

### CODE REVIEW

**Comment by leagris** [comment]
Also fixes issue #8

**Comment by LiaungYip** [comment]
Hi @leagris,

Thanks for your contribution! A few questions:

1) I notice that all XML code has been removed. Are 100% of ATLauncher packs now using config.json instead of config.xml? (Does this include all old versions of packs?)

2) Has this been tested?

    * On new packs?
    * On old packs?
    * On old versions of old packs?
    * On share codes?

**Comment by leagris** [comment]
I did not do these tests on older packs or sharecode.
Anyway, ATLauncher and API now uses JSON queries everywhere.
The JSON Version data is created from the XML, I think even on-the-fly by ATLauncher API

**Comment by leagris** [comment]
This pack has been published 2 years ago. This answer the old packs question:
http://download.nodecdn.net/containers/atl/packs/BeyondReality/versions/1.6.4/Configs.json

**Comment by leagris** [comment]
This pack has been published 2 years ago. This answer the old packs question:
http://download.nodecdn.net/containers/atl/packs/BeyondReality/versions/1.6.4/Configs.json

**Comment by LiaungYip** [comment]
@leagris, if you can test this with:

- an old version of Bevo's Tech Pack, say BTP-11
- a share code
- a new pack

... and post cat herder's console output from those runs, that would convince me that your code is adequately tested with all of cat herder's features.

I am currently tracking and don't have good internet, so I can't do this myself until May.

**Comment by LiaungYip** [comment]
S/tracking/traveling/.

**Comment by leagris** [comment]
Successfully tested with BTP-11 after fixing [extractTo capital T](https://github.com/LiaungYip/Cat-Herder/pull/9/commits/f0ab96eff45dc470215ca2d423f84e0f50569ae4)

* [list_packs](https://gist.githubusercontent.com/leagris/95097f575a138ea6107943ae24791cb7/raw/14a932483174aee53745ed2be1e5cf25eae94f60/gistfile1.txt)
* [BTP-11-Full-install.log](https://gist.github.com/leagris/95097f575a138ea6107943ae24791cb7/raw/14a932483174aee53745ed2be1e5cf25eae94f60/BTP-11-Full-install.log)

I don't know of a pack to test with sharecode.
Now I see no reason for this to fail unless there is a casing/typo issue with one of the dictionary keys from JSON data.

**Pull request merged**
